version: '3'

services:
    web:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./src:/src

    php:
        image: php:fpm-alpine
        build: 
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./src:/src

    composer:
        image: composer:latest
        volumes:
            - ./src:/src
        working_dir: /src
        command: composer dump-autoload

    db:
        image: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./db:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8069:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: root
