version: '3'

services:
    web:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./src:/src

    php:
        image: php:fpm-alpine
        volumes:
            - ./src:/src

    composer:
        image: composer:latest
        volumes:
            - ./src:/src
        working_dir: /src
        command: composer dump-autoload
