version: '3'

services:
    web:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./src:/src

    php:
        image: php:fpm-alpine
        volumes:
            - ./src:/src

    composer:
        image: composer:latest
        volumes:
            - ./src:/src
        working_dir: /src
        command: composer dump-autoload

    db:
        image: mariadb:latest
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        ports:
            - "3306:3306"
        restart: on-failure

    adminer:
        image: adminer:latest
        ports:
            - "8069:8080"
